# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# Checkout the repository
- checkout: self
  fetchDepth: 1

# Use Python 2.7
- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'
  displayName: 'Use Python 2.7'

# Run Python script
- script: |
    python "add.py"
  displayName: 'Run add.py script'

# Inline Python script
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      print('AZURE PIPELINE')
      print('CONTINUOUS INTEGRATION & CONTINUOUS DEPLOYMENT')
  displayName: 'Run inline Python script'
